cc_binary(
    name = "test",
    srcs = ["vcas-parser-test.cc"],
    deps = [
        "//vcas",
        "@gtest",
    ],
)

cc_binary(
    name = "test-manual",
    srcs = ["vcas-client-test.cc"],
    deps = ["//vcas"],
)
